# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Macros.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMainWindow, QMessageBox, QLineEdit


class Ui_Rule_object(QMainWindow):
    def __init__(self):
        super(Ui_Rule_object, self).__init__()
        self.initUI(Rule_object)

    def initUI(self, Rule_object):
        Rule_object.setObjectName("Rule_object")
        Rule_object.resize(600, 675)
        self.rule_table = QtWidgets.QTableWidget(Rule_object)
        self.rule_table.setGeometry(QtCore.QRect(45, 240, 218, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_table.sizePolicy().hasHeightForWidth())
        self.rule_table.setSizePolicy(sizePolicy)
        self.rule_table.setToolTip("")
        self.rule_table.setAutoFillBackground(False)
        self.rule_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.rule_table.setDragEnabled(True)
        self.rule_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.rule_table.setAlternatingRowColors(False)
        self.rule_table.setRowCount(1)
        self.rule_table.setColumnCount(2)
        self.rule_table.setObjectName("rule_table")
        item = QtWidgets.QTableWidgetItem()
        self.rule_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table.setItem(0, 1, item)
        self.rule_table_2 = QtWidgets.QTableWidget(Rule_object)
        self.rule_table_2.setGeometry(QtCore.QRect(345, 240, 218, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_table_2.sizePolicy().hasHeightForWidth())
        self.rule_table_2.setSizePolicy(sizePolicy)
        self.rule_table_2.setToolTip("")
        self.rule_table_2.setAutoFillBackground(False)
        self.rule_table_2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.rule_table_2.setDragEnabled(True)
        self.rule_table_2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.rule_table_2.setAlternatingRowColors(False)
        self.rule_table_2.setRowCount(2)
        self.rule_table_2.setColumnCount(2)
        self.rule_table_2.setObjectName("rule_table_2")

        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_table_2.setItem(1, 1, item)

        self.Label_sheets = QtWidgets.QLabel(Rule_object)
        self.Label_sheets.setGeometry(QtCore.QRect(45, 210, 210, 20))
        self.Label_sheets.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_sheets.setObjectName("Label_sheets")

        self.Label_cell_entries = QtWidgets.QLabel(Rule_object)
        self.Label_cell_entries.setGeometry(QtCore.QRect(345, 210, 210, 20))
        self.Label_cell_entries.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_cell_entries.setObjectName("Label_cell_entries")

        self.lineEdit_macro_title = QtWidgets.QLineEdit(Rule_object)
        self.lineEdit_macro_title.setGeometry(QtCore.QRect(100, 20, 400, 30))
        self.lineEdit_macro_title.setInputMask("")
        self.lineEdit_macro_title.setMaxLength(75)
        self.lineEdit_macro_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_macro_title.setObjectName("lineEdit_macro_title")

        self.Button_add_sheets = QtWidgets.QPushButton(Rule_object)
        self.Button_add_sheets.setGeometry(QtCore.QRect(170, 570, 50, 30))
        self.Button_add_sheets.setAutoDefault(False)
        self.Button_add_sheets.setObjectName("Button_add_sheets")

        self.Button_del_sheets = QtWidgets.QPushButton(Rule_object)
        self.Button_del_sheets.setGeometry(QtCore.QRect(90, 570, 50, 30))
        self.Button_del_sheets.setAutoDefault(False)
        self.Button_del_sheets.setObjectName("Button_del_sheets")

        self.Button_del_cell_entries = QtWidgets.QPushButton(Rule_object)
        self.Button_del_cell_entries.setGeometry(QtCore.QRect(400, 570, 50, 30))
        self.Button_del_cell_entries.setAutoDefault(False)
        self.Button_del_cell_entries.setObjectName("Button_del_cell_entries")

        self.Button_add_cell_entries = QtWidgets.QPushButton(Rule_object)
        self.Button_add_cell_entries.setGeometry(QtCore.QRect(480, 570, 50, 30))
        self.Button_add_cell_entries.setAutoDefault(False)
        self.Button_add_cell_entries.setObjectName("Button_add_cell_entries")

        self.Button_save = QtWidgets.QPushButton(Rule_object)
        self.Button_save.setGeometry(QtCore.QRect(310, 630, 100, 30))
        self.Button_save.setObjectName("Button_save")

        self.Button_cancel = QtWidgets.QPushButton(Rule_object)
        self.Button_cancel.setGeometry(QtCore.QRect(190, 630, 100, 30))
        self.Button_cancel.setAutoDefault(False)
        self.Button_cancel.setObjectName("Button_cancel")

        self.textEdit_macro_description = QtWidgets.QTextEdit(Rule_object)
        self.textEdit_macro_description.setGeometry(QtCore.QRect(20, 70, 560, 100))
        self.textEdit_macro_description.setObjectName("textEdit_macro_description")

        self.retranslateUi(Rule_object)
        QtCore.QMetaObject.connectSlotsByName(Rule_object)

    def retranslateUi(self, Rule_object):
        _translate = QtCore.QCoreApplication.translate
        Rule_object.setWindowTitle(_translate("Rule_object", "Dialog"))
        self.rule_table.setSortingEnabled(True)
        item = self.rule_table.verticalHeaderItem(0)
        item.setText(_translate("Rule_object", "1"))
        item = self.rule_table.horizontalHeaderItem(0)
        item.setText(_translate("Rule_object", "Copy from:"))
        item = self.rule_table.horizontalHeaderItem(1)
        item.setText(_translate("Rule_object", "Paste to:"))
        __sortingEnabled = self.rule_table.isSortingEnabled()
        self.rule_table.setSortingEnabled(False)
        item = self.rule_table.item(0, 0)
        item.setText(_translate("Rule_object", "Sheet 1"))
        item = self.rule_table.item(0, 1)
        item.setText(_translate("Rule_object", "Sheet2"))
        self.rule_table.setSortingEnabled(__sortingEnabled)
        self.rule_table_2.setSortingEnabled(True)
        item = self.rule_table_2.verticalHeaderItem(0)
        item.setText(_translate("Rule_object", "1"))
        item = self.rule_table_2.verticalHeaderItem(1)
        item.setText(_translate("Rule_object", "2"))
        item = self.rule_table_2.horizontalHeaderItem(0)
        item.setText(_translate("Rule_object", "Copy from:"))
        item = self.rule_table_2.horizontalHeaderItem(1)
        item.setText(_translate("Rule_object", "Paste to:"))
        __sortingEnabled = self.rule_table_2.isSortingEnabled()
        self.rule_table_2.setSortingEnabled(False)
        item = self.rule_table_2.item(0, 0)
        item.setText(_translate("Rule_object", "A1"))
        item = self.rule_table_2.item(0, 1)
        item.setText(_translate("Rule_object", "B2"))
        item = self.rule_table_2.item(1, 0)
        item.setText(_translate("Rule_object", "C2:C4"))
        item = self.rule_table_2.item(1, 1)
        item.setText(_translate("Rule_object", "D3:D5"))
        self.rule_table_2.setSortingEnabled(__sortingEnabled)
        self.Label_sheets.setText(_translate("Rule_object", "Sheets"))
        self.Label_cell_entries.setText(_translate("Rule_object", "Cell Entries"))
        self.lineEdit_macro_title.setPlaceholderText(_translate("Rule_object", "Enter Macro Title"))
        self.Button_add_sheets.setText(_translate("Rule_object", "+"))
        self.Button_del_sheets.setText(_translate("Rule_object", "-"))
        self.Button_del_cell_entries.setText(_translate("Rule_object", "-"))
        self.Button_add_cell_entries.setText(_translate("Rule_object", "+"))
        self.Button_save.setText(_translate("Rule_object", "Save"))
        self.Button_cancel.setText(_translate("Rule_object", "Cancel"))
        self.textEdit_macro_description.setPlaceholderText(_translate("Rule_object", "Enter Macro Descriptions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rule_object = QtWidgets.QDialog()
    ui = Ui_Rule_object()
    ui.initUI(Rule_object)
    Rule_object.show()
    sys.exit(app.exec_())

